// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
//
// This file is kept beside the additive invocation protobuf generated types.

package dtmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	ResourceInvocationService_InvokeResource_FullMethodName = "/dtm.v1.ResourceInvocationService/InvokeResource"
)

// ResourceInvocationServiceClient is the client API for ResourceInvocationService.
type ResourceInvocationServiceClient interface {
	InvokeResource(ctx context.Context, in *InvocationRequest, opts ...grpc.CallOption) (*InvocationResponse, error)
}

type resourceInvocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceInvocationServiceClient(cc grpc.ClientConnInterface) ResourceInvocationServiceClient {
	return &resourceInvocationServiceClient{cc}
}

func (c *resourceInvocationServiceClient) InvokeResource(ctx context.Context, in *InvocationRequest, opts ...grpc.CallOption) (*InvocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvocationResponse)
	err := c.cc.Invoke(ctx, ResourceInvocationService_InvokeResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceInvocationServiceServer is the server API for ResourceInvocationService.
// All implementations must embed UnimplementedResourceInvocationServiceServer
// for forward compatibility.
type ResourceInvocationServiceServer interface {
	InvokeResource(context.Context, *InvocationRequest) (*InvocationResponse, error)
	mustEmbedUnimplementedResourceInvocationServiceServer()
}

// UnimplementedResourceInvocationServiceServer must be embedded to have
// forward compatible implementations.
type UnimplementedResourceInvocationServiceServer struct{}

func (UnimplementedResourceInvocationServiceServer) InvokeResource(context.Context, *InvocationRequest) (*InvocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeResource not implemented")
}

func (UnimplementedResourceInvocationServiceServer) mustEmbedUnimplementedResourceInvocationServiceServer() {
}
func (UnimplementedResourceInvocationServiceServer) testEmbeddedByValue() {}

// UnsafeResourceInvocationServiceServer may be embedded to opt out of forward compatibility.
// Use of this interface is not recommended, as added methods to ResourceInvocationServiceServer
// will result in compilation errors.
type UnsafeResourceInvocationServiceServer interface {
	mustEmbedUnimplementedResourceInvocationServiceServer()
}

func RegisterResourceInvocationServiceServer(s grpc.ServiceRegistrar, srv ResourceInvocationServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceInvocationService_ServiceDesc, srv)
}

func _ResourceInvocationService_InvokeResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceInvocationServiceServer).InvokeResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceInvocationService_InvokeResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceInvocationServiceServer).InvokeResource(ctx, req.(*InvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceInvocationService_ServiceDesc is the grpc.ServiceDesc for ResourceInvocationService.
// It is intended for direct use with grpc.RegisterService and not for mutation.
var ResourceInvocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dtm.v1.ResourceInvocationService",
	HandlerType: (*ResourceInvocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeResource",
			Handler:    _ResourceInvocationService_InvokeResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dtm/v1/invocation.proto",
}
