// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.13.0
// source: dtm/v1/invocation.proto

package dtmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceRef is the complete authority-bound identity carried by native
// invocation requests. Endpoint and transport selection deliberately remain
// outside this message.
type ResourceRef struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResourceId          string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceGeneration  uint64                 `protobuf:"varint,2,opt,name=resource_generation,json=resourceGeneration,proto3" json:"resource_generation,omitempty"`
	OwnerNodeId         string                 `protobuf:"bytes,3,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	OwnerNodeGeneration int64                  `protobuf:"varint,4,opt,name=owner_node_generation,json=ownerNodeGeneration,proto3" json:"owner_node_generation,omitempty"`
	RegistrationId      string                 `protobuf:"bytes,5,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_dtm_v1_invocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_dtm_v1_invocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_dtm_v1_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRef) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourceRef) GetResourceGeneration() uint64 {
	if x != nil {
		return x.ResourceGeneration
	}
	return 0
}

func (x *ResourceRef) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

func (x *ResourceRef) GetOwnerNodeGeneration() int64 {
	if x != nil {
		return x.OwnerNodeGeneration
	}
	return 0
}

func (x *ResourceRef) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type InvocationMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StepId         string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Attempt        uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Duration in milliseconds. Zero means that the caller supplies no
	// additional invocation deadline, matching the domain contract.
	TimeoutMillis int64 `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationMetadata) Reset() {
	*x = InvocationMetadata{}
	mi := &file_dtm_v1_invocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationMetadata) ProtoMessage() {}

func (x *InvocationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dtm_v1_invocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationMetadata.ProtoReflect.Descriptor instead.
func (*InvocationMetadata) Descriptor() ([]byte, []int) {
	return file_dtm_v1_invocation_proto_rawDescGZIP(), []int{1}
}

func (x *InvocationMetadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InvocationMetadata) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *InvocationMetadata) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *InvocationMetadata) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvocationMetadata) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type InvocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  []byte                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	ResourceRef   *ResourceRef           `protobuf:"bytes,2,opt,name=resource_ref,json=resourceRef,proto3" json:"resource_ref,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *InvocationMetadata    `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationRequest) Reset() {
	*x = InvocationRequest{}
	mi := &file_dtm_v1_invocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationRequest) ProtoMessage() {}

func (x *InvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtm_v1_invocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationRequest.ProtoReflect.Descriptor instead.
func (*InvocationRequest) Descriptor() ([]byte, []int) {
	return file_dtm_v1_invocation_proto_rawDescGZIP(), []int{2}
}

func (x *InvocationRequest) GetInvocationId() []byte {
	if x != nil {
		return x.InvocationId
	}
	return nil
}

func (x *InvocationRequest) GetResourceRef() *ResourceRef {
	if x != nil {
		return x.ResourceRef
	}
	return nil
}

func (x *InvocationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *InvocationRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvocationRequest) GetMetadata() *InvocationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InvocationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  []byte                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationResult) Reset() {
	*x = InvocationResult{}
	mi := &file_dtm_v1_invocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationResult) ProtoMessage() {}

func (x *InvocationResult) ProtoReflect() protoreflect.Message {
	mi := &file_dtm_v1_invocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationResult.ProtoReflect.Descriptor instead.
func (*InvocationResult) Descriptor() ([]byte, []int) {
	return file_dtm_v1_invocation_proto_rawDescGZIP(), []int{3}
}

func (x *InvocationResult) GetInvocationId() []byte {
	if x != nil {
		return x.InvocationId
	}
	return nil
}

func (x *InvocationResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InvocationError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvocationId   []byte                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable      bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	OutcomeUnknown bool                   `protobuf:"varint,5,opt,name=outcome_unknown,json=outcomeUnknown,proto3" json:"outcome_unknown,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Classification string                 `protobuf:"bytes,7,opt,name=classification,proto3" json:"classification,omitempty"`
	DispatchState  string                 `protobuf:"bytes,8,opt,name=dispatch_state,json=dispatchState,proto3" json:"dispatch_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvocationError) Reset() {
	*x = InvocationError{}
	mi := &file_dtm_v1_invocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationError) ProtoMessage() {}

func (x *InvocationError) ProtoReflect() protoreflect.Message {
	mi := &file_dtm_v1_invocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationError.ProtoReflect.Descriptor instead.
func (*InvocationError) Descriptor() ([]byte, []int) {
	return file_dtm_v1_invocation_proto_rawDescGZIP(), []int{4}
}

func (x *InvocationError) GetInvocationId() []byte {
	if x != nil {
		return x.InvocationId
	}
	return nil
}

func (x *InvocationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InvocationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvocationError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *InvocationError) GetOutcomeUnknown() bool {
	if x != nil {
		return x.OutcomeUnknown
	}
	return false
}

func (x *InvocationError) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InvocationError) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *InvocationError) GetDispatchState() string {
	if x != nil {
		return x.DispatchState
	}
	return ""
}

type InvocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*InvocationResponse_Result
	//	*InvocationResponse_Error
	Outcome       isInvocationResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationResponse) Reset() {
	*x = InvocationResponse{}
	mi := &file_dtm_v1_invocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationResponse) ProtoMessage() {}

func (x *InvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtm_v1_invocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationResponse.ProtoReflect.Descriptor instead.
func (*InvocationResponse) Descriptor() ([]byte, []int) {
	return file_dtm_v1_invocation_proto_rawDescGZIP(), []int{5}
}

func (x *InvocationResponse) GetOutcome() isInvocationResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *InvocationResponse) GetResult() *InvocationResult {
	if x != nil {
		if x, ok := x.Outcome.(*InvocationResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *InvocationResponse) GetError() *InvocationError {
	if x != nil {
		if x, ok := x.Outcome.(*InvocationResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isInvocationResponse_Outcome interface {
	isInvocationResponse_Outcome()
}

type InvocationResponse_Result struct {
	Result *InvocationResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type InvocationResponse_Error struct {
	Error *InvocationError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*InvocationResponse_Result) isInvocationResponse_Outcome() {}

func (*InvocationResponse_Error) isInvocationResponse_Outcome() {}

var File_dtm_v1_invocation_proto protoreflect.FileDescriptor

const file_dtm_v1_invocation_proto_rawDesc = "" +
	"\n" +
	"\x17dtm/v1/invocation.proto\x12\x06dtm.v1\"\xe0\x01\n" +
	"\vResourceRef\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12/\n" +
	"\x13resource_generation\x18\x02 \x01(\x04R\x12resourceGeneration\x12\"\n" +
	"\rowner_node_id\x18\x03 \x01(\tR\vownerNodeId\x122\n" +
	"\x15owner_node_generation\x18\x04 \x01(\x03R\x13ownerNodeGeneration\x12'\n" +
	"\x0fregistration_id\x18\x05 \x01(\tR\x0eregistrationId\"\xb0\x01\n" +
	"\x12InvocationMetadata\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x03R\rtimeoutMillis\"\xe5\x01\n" +
	"\x11InvocationRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\fR\finvocationId\x126\n" +
	"\fresource_ref\x18\x02 \x01(\v2\x13.dtm.v1.ResourceRefR\vresourceRef\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x126\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1a.dtm.v1.InvocationMetadataR\bmetadata\"Q\n" +
	"\x10InvocationResult\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\fR\finvocationId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x92\x02\n" +
	"\x0fInvocationError\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\fR\finvocationId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12'\n" +
	"\x0foutcome_unknown\x18\x05 \x01(\bR\x0eoutcomeUnknown\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12&\n" +
	"\x0eclassification\x18\a \x01(\tR\x0eclassification\x12%\n" +
	"\x0edispatch_state\x18\b \x01(\tR\rdispatchState\"\x84\x01\n" +
	"\x12InvocationResponse\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x18.dtm.v1.InvocationResultH\x00R\x06result\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.dtm.v1.InvocationErrorH\x00R\x05errorB\t\n" +
	"\aoutcome2d\n" +
	"\x19ResourceInvocationService\x12G\n" +
	"\x0eInvokeResource\x12\x19.dtm.v1.InvocationRequest\x1a\x1a.dtm.v1.InvocationResponseB\x1cZ\x1adtm/api/proto/dtm/v1;dtmv1b\x06proto3"

var (
	file_dtm_v1_invocation_proto_rawDescOnce sync.Once
	file_dtm_v1_invocation_proto_rawDescData []byte
)

func file_dtm_v1_invocation_proto_rawDescGZIP() []byte {
	file_dtm_v1_invocation_proto_rawDescOnce.Do(func() {
		file_dtm_v1_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtm_v1_invocation_proto_rawDesc), len(file_dtm_v1_invocation_proto_rawDesc)))
	})
	return file_dtm_v1_invocation_proto_rawDescData
}

var file_dtm_v1_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dtm_v1_invocation_proto_goTypes = []any{
	(*ResourceRef)(nil),        // 0: dtm.v1.ResourceRef
	(*InvocationMetadata)(nil), // 1: dtm.v1.InvocationMetadata
	(*InvocationRequest)(nil),  // 2: dtm.v1.InvocationRequest
	(*InvocationResult)(nil),   // 3: dtm.v1.InvocationResult
	(*InvocationError)(nil),    // 4: dtm.v1.InvocationError
	(*InvocationResponse)(nil), // 5: dtm.v1.InvocationResponse
}
var file_dtm_v1_invocation_proto_depIdxs = []int32{
	0, // 0: dtm.v1.InvocationRequest.resource_ref:type_name -> dtm.v1.ResourceRef
	1, // 1: dtm.v1.InvocationRequest.metadata:type_name -> dtm.v1.InvocationMetadata
	3, // 2: dtm.v1.InvocationResponse.result:type_name -> dtm.v1.InvocationResult
	4, // 3: dtm.v1.InvocationResponse.error:type_name -> dtm.v1.InvocationError
	2, // 4: dtm.v1.ResourceInvocationService.InvokeResource:input_type -> dtm.v1.InvocationRequest
	5, // 5: dtm.v1.ResourceInvocationService.InvokeResource:output_type -> dtm.v1.InvocationResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dtm_v1_invocation_proto_init() }
func file_dtm_v1_invocation_proto_init() {
	if File_dtm_v1_invocation_proto != nil {
		return
	}
	file_dtm_v1_invocation_proto_msgTypes[5].OneofWrappers = []any{
		(*InvocationResponse_Result)(nil),
		(*InvocationResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtm_v1_invocation_proto_rawDesc), len(file_dtm_v1_invocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dtm_v1_invocation_proto_goTypes,
		DependencyIndexes: file_dtm_v1_invocation_proto_depIdxs,
		MessageInfos:      file_dtm_v1_invocation_proto_msgTypes,
	}.Build()
	File_dtm_v1_invocation_proto = out.File
	file_dtm_v1_invocation_proto_goTypes = nil
	file_dtm_v1_invocation_proto_depIdxs = nil
}
